import argparse


def parse_args():    
    parser = argparse.ArgumentParser()
    parser.add_argument('-net', type=str, default='sam2', help='net type')
    parser.add_argument('-exp_name', default='samba_train_test', type=str, help='experiment name')
    parser.add_argument('-vis', type=bool, default=False, help='Generate visualisation during validation')
    parser.add_argument('-pretrain', type=str, default=None, help='path of pretrain weights')
    parser.add_argument('-val_freq',type=int,default=5,help='interval between each validation')
    parser.add_argument('-gpu', type=bool, default=True, help='use gpu or not')
    parser.add_argument('-gpu_device', type=int, default=0, help='use which gpu')
    parser.add_argument('-image_size', type=int, default=1024, help='image_size')
    parser.add_argument('-out_size', type=int, default=1024, help='output_size')
    parser.add_argument('-distributed', default='none' ,type=str,help='multi GPU ids to use')
    parser.add_argument('-dataset', default='BUSI' ,type=str,help='dataset name')
    parser.add_argument('-sam_ckpt', type=str, default=None , help='sam checkpoint address')
    parser.add_argument('-sam_config', type=str, default=None , help='sam checkpoint address')
    parser.add_argument('-b', type=int, default=1, help='batch size for dataloader')
    parser.add_argument('-lr', type=float, default=1e-4, help='initial learning rate')
    parser.add_argument('-epoch', type=int, default=150, help='epoch number')
    parser.add_argument('-weights', type=str, default = 0, help='the weights file you want to test')
    parser.add_argument('-multimask_output', type=bool, default=False , help='the number of masks output for multi-class segmentation')
    parser.add_argument('-memory_bank_size', type=int, default=16, help='sam 2d memory bank size')
    parser.add_argument('-data_path', type=str, default='./data/BUSI', help='The path of segmentation data')
    parser.add_argument('-DiceCEloss', type=bool, default=False, help='use DiceCELoss')
    parser.add_argument('-model_name', type=str, default='biomedical-sam2', help='model name, biomedical-sam2/sam2/...')
    parser.add_argument('-nprompt', type=str, default='click', help='type of prompt, bbox or click')
    parser.add_argument('-seed', type=int, default=42, help='seed')
    parser.add_argument('-ood', type=str, default=None, help='val ood data or not')
    parser.add_argument('-train_file_dir', type=str, default=None, help='train path file')
    parser.add_argument('-val_file_dir', type=str, default=None, help='val path file')
    opt = parser.parse_args()

    return opt
